### Uusi blöggers
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "New Blog Titteli",
  "author": "Test Author",
  "url": "http://example.com",
  "likes": 10,
  "userId": "67a9c5fb5bda10d365e21944"
}

### Hanki kaikki
GET http://localhost:3001/api/blogs

### Poisto
DELETE http://localhost:3001/api/blogs/67a9c94084333b363e9bf3bb

### Ei toimiva bloggers
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "e3pävalmis höskä"
}

### Käyttäjien lisääminen
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "newuser",
  "name": "New User",
  "password": "newpassword"
}

### käyttäjien hakeminen
GET http://localhost:3001/api/users
